# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

# resources:
#   repositories:
#   - repository: string  # identifier (A-Z, a-z, 0-9, and underscore)
#     type: github  # see the following "Type" topic
#     name: string  # repository name (format depends on `type`)
#     ref: string  # ref name to use; defaults to 'refs/heads/main'
#     endpoint: string  # name of the service connection to use (for types that aren't Azure Repos)
#     trigger:  # CI trigger for this repository, no CI trigger if skipped (only works for Azure Repos)
#       branches:
#         include: [ string ] # branch names which trigger a build

#       tags:
#         include: [ string ] # tag names which trigger a build
#         exclude: [ string ] # tag names which won't
#       paths:
#         include: [ string ] # file paths which must match to trigger a build
#         exclude: [ string ] # file paths which won't trigger a build

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

# - script: |
#     python -m venv antenv
#     source antenv/bin/activate
#     python -m pip install --upgrade pip
#     pip install setup
#     pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
#   workingDirectory: $(projectRoot)
#   displayName: "Install requirements"

- task: ArchiveFiles@2
  inputs:
     rootFolderOrFile: '$(Build.SourcesDirectory)'
     includeRootFolder: false
     archiveType: 'zip'
     archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
     replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip
  displayName: 'Upload package'
  artifact: drop

- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: 'UdacityDS - 81 (7de72e36-dc87-4e3f-aa67-6dacbc9993c6)-1512'
    appType: 'webAppLinux'
    WebAppName: 'udacity-pythonwebapp'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    RuntimeStack: 'PYTHON|3.7'
